version: '3.2'



services:
  server:
    image: registry.schreib.io/tsv-forstenried/handballtag/server/server
    build: ./docker/rest
    hostname: server
    ports:
      - "8080:8080"
      - "8081:8081"
    expose:
      - 8080
      - 8081
    depends_on:
      - postgres

  postgres:
      image: registry.schreib.io/tsv-forstenried/handballtag/server/postgres
      build: ./docker/postgres
      hostname: postgres
      ports:
        - "35432:5432"
      environment:
        TZ: CET
        POSTGRES_DB: handballtag
        POSTGRES_USER: handball
        POSTGRES_PASSWORD: JIHoiuo3i2rkbfd
      expose:
        - 35432

volumes:
    spirit2-dbdata: