version: '3.2'

networks:
  handballtag-cluster:
    driver: bridge
  handballtag-backend:
    driver: bridge


services:
  server:
    image: registry.schreib.io/tsv-forstenried/handballtag/server/server
    build: ./docker/rest
    hostname: server
    ports:
      - "8080:8080"
      - "8081:8081"
    expose:
      - 8080
      - 8081
    depends_on:
      - postgres
    networks:
      handballtag-cluster:
        aliases:
          - server
      handballtag-backend:
        aliases:
          - server

  postgres:
    image: registry.schreib.io/tsv-forstenried/handballtag/server/postgres
    build: ./docker/postgres
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      TZ: CET
    expose:
      - 5432
    networks:
      handballtag-backend:
        aliases:
          - postgres